from __future__ import annotations

from pathlib import Path


RAIZ_RISKO = Path(__file__).resolve().parents[2]
CARPETA_RIESGO_MERCADO = RAIZ_RISKO.parent
CARPETA_GERENCIA_TESORERIA = CARPETA_RIESGO_MERCADO.parent

CARPETA_APLICACIONES = RAIZ_RISKO / "aplicaciones"
CARPETA_COMPARTIDO = RAIZ_RISKO / "compartido"
CARPETA_PROYECTOS = RAIZ_RISKO / "proyectos"
CARPETA_DATOS = RAIZ_RISKO / "datos"
CARPETA_INSUMOS = CARPETA_DATOS / "insumos"
CARPETA_EJECUCIONES = RAIZ_RISKO / "ejecuciones"
CARPETA_HERRAMIENTAS = RAIZ_RISKO / "Herramientas"

# Produccion del portal. El codigo fuente permanece en Proyecto Risko, mientras
# que esta biblioteca compartida contiene solamente ejecutables, dashboards y
# configuraciones operativas.
CARPETA_PORTAL_RIESGOS_MERCADO = (
    CARPETA_GERENCIA_TESORERIA / "Portal Riesgos de Mercado"
)
CARPETA_DASHBOARDS_PORTAL = CARPETA_PORTAL_RIESGOS_MERCADO / "Dashboards"
CARPETA_APLICACIONES_PORTAL = CARPETA_PORTAL_RIESGOS_MERCADO / "Aplicaciones"
CARPETA_CONFIGURACIONES_PORTAL = (
    CARPETA_PORTAL_RIESGOS_MERCADO / "Configuraciones"
)
CARPETA_RELEASES_PORTAL = CARPETA_PORTAL_RIESGOS_MERCADO / "releases"

CARPETA_POSITION_MONITOR = CARPETA_PROYECTOS / "position_monitor"
CARPETA_CONFIG_POSITION_MONITOR = CARPETA_POSITION_MONITOR / "configuracion"
CARPETA_DOCUMENTACION_POSITION_MONITOR = CARPETA_POSITION_MONITOR / "documentacion"
CARPETA_PROCESOS_POSITION_MONITOR = CARPETA_POSITION_MONITOR / "procesos"
CARPETA_TABLEROS_POSITION_MONITOR = CARPETA_POSITION_MONITOR / "tableros"

CARPETA_DATOS_POSITION_MONITOR = CARPETA_DATOS / "position_monitor"
CARPETA_INSUMOS_POSITION_MONITOR = CARPETA_INSUMOS
CARPETA_PROCESADOS_POSITION_MONITOR = CARPETA_DATOS_POSITION_MONITOR / "procesados"
CARPETA_PUBLICADOS_POSITION_MONITOR = CARPETA_DATOS_POSITION_MONITOR / "publicados"
CARPETA_INTRADIA_POSITION_MONITOR = CARPETA_DATOS_POSITION_MONITOR / "intradia"
CARPETA_INSUMOS_INTRADIA_POSITION_MONITOR = CARPETA_INTRADIA_POSITION_MONITOR / "insumos"
CARPETA_PROCESADOS_INTRADIA_POSITION_MONITOR = CARPETA_INTRADIA_POSITION_MONITOR / "procesados"
CARPETA_PUBLICADOS_INTRADIA_POSITION_MONITOR = CARPETA_INTRADIA_POSITION_MONITOR / "publicados"
CARPETA_PRUEBAS_POSITION_MONITOR = CARPETA_DATOS_POSITION_MONITOR / "pruebas"
CARPETA_PRUEBAS_SPOT_2 = CARPETA_PRUEBAS_POSITION_MONITOR / "spot_2"
CARPETA_PRUEBAS_SPOT_2_CIERRE = CARPETA_PRUEBAS_SPOT_2 / "cierre"
CARPETA_INSUMOS_SPOT_2_CIERRE = CARPETA_PRUEBAS_SPOT_2_CIERRE / "insumos"
CARPETA_BASE_DATOS = CARPETA_DATOS / "base de datos"

ARCHIVO_BASE_DATOS_RISKO = CARPETA_BASE_DATOS / "risko.db"
ARCHIVO_BASE_DATOS_RISKO_PRUEBAS = CARPETA_BASE_DATOS / "risko_pruebas.db"
# ADICION AUXILIAR: base independiente para soportes e intermedios de todos los modulos.
ARCHIVO_BASE_DATOS_RISKO_AUXILIAR = CARPETA_BASE_DATOS / "risko_auxiliar.db"
ARCHIVO_BASE_DATOS_POSITION_MONITOR = ARCHIVO_BASE_DATOS_RISKO
ARCHIVO_BASE_DATOS_RISKO_INTRADIA = CARPETA_INTRADIA_POSITION_MONITOR / "risko_intradia.db"
ARCHIVO_BASE_DATOS_SPOT_2_CIERRE_PRUEBAS = (
    CARPETA_PRUEBAS_SPOT_2_CIERRE / "risko_spot_2_cierre_pruebas.db"
)
ARCHIVO_PANEL_POSITION_MONITOR_INTRADIA = (
    CARPETA_PUBLICADOS_INTRADIA_POSITION_MONITOR / "panel_position_monitor_preliminar.html"
)

ARCHIVO_PARAM_RUTAS = CARPETA_CONFIG_POSITION_MONITOR / "param_rutas.csv"
ARCHIVO_PARAM_LIBROS = CARPETA_CONFIG_POSITION_MONITOR / "param_libros.csv"
ARCHIVO_PARAM_SPOT_2 = CARPETA_CONFIG_POSITION_MONITOR / "param_spot_2.csv"
ARCHIVO_PARAM_LIBRORF = CARPETA_CONFIG_POSITION_MONITOR / "param_librorf.csv"
ARCHIVO_PARAM_MONEDARF = CARPETA_CONFIG_POSITION_MONITOR / "param_monedarf.csv"

ARCHIVO_POSICION_ACTUAL = CARPETA_PUBLICADOS_POSITION_MONITOR / "tbl_posicion_actual.csv"
ARCHIVO_POSICION_HISTORICO = CARPETA_PUBLICADOS_POSITION_MONITOR / "tbl_posicion_historico.csv"
ARCHIVO_PANEL_POSITION_MONITOR = CARPETA_PUBLICADOS_POSITION_MONITOR / "panel_position_monitor.html"
ARCHIVO_POSICION_CONSOLIDADA = CARPETA_PROCESADOS_POSITION_MONITOR / "tbl_posicion_consolidada.csv"

ARCHIVO_INSUMO_NOVADOS_DEPURADO = CARPETA_PROCESADOS_POSITION_MONITOR / "df_Insumo.xlsx"
ARCHIVO_INSUMO_SPOT_DEPURADO = CARPETA_PROCESADOS_POSITION_MONITOR / "df_Insumo_spot.xlsx"
ARCHIVO_SALIDA_NOVADOS = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Novados.csv"
ARCHIVO_SALIDA_NOVADOS_LEGACY = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Novados_Posicion.csv"
ARCHIVO_INSUMO_FORWARD_DEPURADO = CARPETA_PROCESADOS_POSITION_MONITOR / "df_Insumo_FWD.xlsx"
ARCHIVO_INSUMO_FORWARD_IFRS_DEPURADO = CARPETA_PROCESADOS_POSITION_MONITOR / "df_Insumo_FWD_IFRS.xlsx"
ARCHIVO_SALIDA_FORWARD_TABLA = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Forward.csv"
ARCHIVO_SALIDA_FORWARD_BANKING = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_FWD.xlsx"
ARCHIVO_SALIDA_FORWARD_IFRS = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_FWD_IFRS.xlsx"
ARCHIVO_SALIDA_FORWARD_CVA_DVA = CARPETA_PROCESADOS_POSITION_MONITOR / "df_Fwd_CVADVA.xlsx"
ARCHIVO_SALIDA_FORWARD = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_pruebas.xlsx"
ARCHIVO_INSUMO_OPCIONES_DEPURADO = CARPETA_PROCESADOS_POSITION_MONITOR / "Df_Insumo_Opciones_Depurado.xlsx"
ARCHIVO_SALIDA_OPCIONES_TABLA = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Opciones.csv"
ARCHIVO_SALIDA_SWAPS_TABLA = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Swaps.csv"
ARCHIVO_SALIDA_SWAPS_TABLA_DETALLE = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Swaps_Detalle.csv"
ARCHIVO_SALIDA_SWAPS_DETALLE = CARPETA_PROCESADOS_POSITION_MONITOR / "Df_Insumo_Swaps_Depurado.xlsx"
ARCHIVO_SALIDA_RENTA_FIJA_TABLA = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicion_Renta_Fija.csv"
ARCHIVO_SALIDA_RENTA_FIJA = CARPETA_PROCESADOS_POSITION_MONITOR / "Tbl_Posicionrf.xlsx"
ARCHIVO_DETALLE_RENTA_FIJA = CARPETA_PROCESADOS_POSITION_MONITOR / "Posicionrf.xlsx"

ARCHIVO_LOCAL_OPCIONES_MERCADO = CARPETA_INSUMOS / "ENTRADA2.xlsb"
ARCHIVO_LOCAL_CURVA_FORWARD = CARPETA_INSUMOS / "Curva Forward V2.xlsm"
ARCHIVO_LOCAL_INSUMO_TASAS = CARPETA_INSUMOS / "Insumo tasas.xlsx"
CARPETA_FUENTE_BDB = CARPETA_RIESGO_MERCADO / "BDB"
CARPETA_FUENTE_OPCIONES = Path(r"\\SUMMITFS001\apl\Internos\GR\FXOPTION_BASIC")
ARCHIVO_FUENTE_OPCIONES_MERCADO = CARPETA_FUENTE_BDB / "ENTRADA2.xlsb"
ARCHIVO_FUENTE_CURVA_FORWARD = CARPETA_RIESGO_MERCADO / "Datos Mercado" / "Curva Forward V2.xlsm"
ARCHIVO_INSUMO_TASAS = (
    CARPETA_GERENCIA_TESORERIA
    / "2 Jefatura de Compliance de Tesorería"
    / "Insumos CT"
    / "Tasas"
    / "Insumo tasas.xlsx"
)
ARCHIVO_CONFIG_RISKO_VECTOR = CARPETA_CONFIG_POSITION_MONITOR / "risko.json"
ARCHIVO_VECTOR_PY = CARPETA_HERRAMIENTAS / "VECTOR" / "VECTOR.py"

CARPETA_LOGS_POSITION_MONITOR = CARPETA_EJECUCIONES / "position_monitor" / "logs"
CARPETA_DASHY_POR_DEFECTO = CARPETA_HERRAMIENTAS / "dashy"


def resolver_ruta_importacion_dashy(ruta_dashy: str | Path | None = None) -> Path:
    ruta_base = Path(ruta_dashy) if ruta_dashy else CARPETA_DASHY_POR_DEFECTO

    if ruta_base.name.lower() == "dashy" and (ruta_base / "__init__.py").exists():
        return ruta_base.parent

    if (ruta_base / "dashy" / "__init__.py").exists():
        return ruta_base

    raise FileNotFoundError(
        "No se encontro una carpeta valida de dashy. "
        f"Ruta recibida: {ruta_base}"
    )


def asegurar_directorios() -> None:
    for carpeta in (
        CARPETA_APLICACIONES,
        CARPETA_COMPARTIDO,
        CARPETA_PROYECTOS,
        CARPETA_DATOS,
        CARPETA_BASE_DATOS,
        CARPETA_INSUMOS,
        CARPETA_EJECUCIONES,
        CARPETA_HERRAMIENTAS,
        CARPETA_POSITION_MONITOR,
        CARPETA_CONFIG_POSITION_MONITOR,
        CARPETA_DOCUMENTACION_POSITION_MONITOR,
        CARPETA_PROCESOS_POSITION_MONITOR,
        CARPETA_TABLEROS_POSITION_MONITOR,
        CARPETA_DATOS_POSITION_MONITOR,
        CARPETA_PROCESADOS_POSITION_MONITOR,
        CARPETA_PUBLICADOS_POSITION_MONITOR,
        CARPETA_INTRADIA_POSITION_MONITOR,
        CARPETA_INSUMOS_INTRADIA_POSITION_MONITOR,
        CARPETA_PROCESADOS_INTRADIA_POSITION_MONITOR,
        CARPETA_PUBLICADOS_INTRADIA_POSITION_MONITOR,
        CARPETA_PRUEBAS_POSITION_MONITOR,
        CARPETA_PRUEBAS_SPOT_2,
        CARPETA_PRUEBAS_SPOT_2_CIERRE,
        CARPETA_INSUMOS_SPOT_2_CIERRE,
        CARPETA_LOGS_POSITION_MONITOR,
    ):
        carpeta.mkdir(parents=True, exist_ok=True)
